version: '3'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # environment variable
      POSTGRES_DB: second-brain
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  cache:
    image: redis:latest
    ports:
      - '6379:6379'
volumes:
  db-data:
